// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1) {
  return window['go']['main']['Database']['AddBookmark'](arg1);
}

export function AddFavorite(arg1) {
  return window['go']['main']['Database']['AddFavorite'](arg1);
}

export function AddHistory(arg1) {
  return window['go']['main']['Database']['AddHistory'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['Database']['ClearHistory']();
}

export function GetBookmarks() {
  return window['go']['main']['Database']['GetBookmarks']();
}

export function GetFavorites() {
  return window['go']['main']['Database']['GetFavorites']();
}

export function GetHistory() {
  return window['go']['main']['Database']['GetHistory']();
}

export function GetSettings() {
  return window['go']['main']['Database']['GetSettings']();
}

export function Init() {
  return window['go']['main']['Database']['Init']();
}

export function IsBookmarked(arg1, arg2) {
  return window['go']['main']['Database']['IsBookmarked'](arg1, arg2);
}

export function IsFavorite(arg1, arg2) {
  return window['go']['main']['Database']['IsFavorite'](arg1, arg2);
}

export function RemoveBookmark(arg1, arg2) {
  return window['go']['main']['Database']['RemoveBookmark'](arg1, arg2);
}

export function RemoveFavorite(arg1, arg2) {
  return window['go']['main']['Database']['RemoveFavorite'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['Database']['SaveSettings'](arg1);
}
