// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBookmark(arg1:main.Bookmark):Promise<void>;

export function AddFavorite(arg1:main.Favorite):Promise<void>;

export function AddHistory(arg1:main.History):Promise<void>;

export function ClearHistory():Promise<void>;

export function GetBookmarks():Promise<Array<main.Bookmark>>;

export function GetFavorites():Promise<Array<main.Favorite>>;

export function GetHistory():Promise<Array<main.History>>;

export function GetSettings():Promise<main.Settings>;

export function Init():Promise<void>;

export function IsBookmarked(arg1:number,arg2:string):Promise<boolean>;

export function IsFavorite(arg1:number,arg2:string):Promise<boolean>;

export function RemoveBookmark(arg1:number,arg2:string):Promise<void>;

export function RemoveFavorite(arg1:number,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
