// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetIndexers():Promise<Array<main.IndexerConfig>>;

export function Search(arg1:string,arg2:Array<number>):Promise<main.JackettResponse>;

export function SearchAnime(arg1:string):Promise<main.JackettResponse>;

export function SearchByIndexer(arg1:string,arg2:string,arg3:Array<number>):Promise<main.JackettResponse>;

export function SearchMovies(arg1:string):Promise<main.JackettResponse>;

export function SearchTV(arg1:string):Promise<main.JackettResponse>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function TestConnection():Promise<boolean>;
