// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIndexers() {
  return window['go']['main']['Jackett']['GetIndexers']();
}

export function Search(arg1, arg2) {
  return window['go']['main']['Jackett']['Search'](arg1, arg2);
}

export function SearchAnime(arg1) {
  return window['go']['main']['Jackett']['SearchAnime'](arg1);
}

export function SearchByIndexer(arg1, arg2, arg3) {
  return window['go']['main']['Jackett']['SearchByIndexer'](arg1, arg2, arg3);
}

export function SearchMovies(arg1) {
  return window['go']['main']['Jackett']['SearchMovies'](arg1);
}

export function SearchTV(arg1) {
  return window['go']['main']['Jackett']['SearchTV'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['Jackett']['SetConfig'](arg1, arg2);
}

export function TestConnection() {
  return window['go']['main']['Jackett']['TestConnection']();
}
