// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAnimationMovies(arg1:number):Promise<main.SearchResult>;

export function GetAnimationTV(arg1:number):Promise<main.TVSearchResult>;

export function GetCollection(arg1:number):Promise<main.CollectionDetails>;

export function GetGenres():Promise<Array<main.Genre>>;

export function GetImageURL(arg1:string,arg2:string):Promise<string>;

export function GetMovieDetails(arg1:number):Promise<main.MovieDetails>;

export function GetMovieRecommendations(arg1:number):Promise<main.SearchResult>;

export function GetMovieSimilar(arg1:number):Promise<main.SearchResult>;

export function GetMovieVideos(arg1:number):Promise<main.VideosResult>;

export function GetPopularMovies(arg1:number):Promise<main.SearchResult>;

export function GetPopularTV(arg1:number):Promise<main.TVSearchResult>;

export function GetSeasonDetails(arg1:number,arg2:number):Promise<main.SeasonDetails>;

export function GetTVDetails(arg1:number):Promise<main.TVShowDetails>;

export function GetTVGenres():Promise<Array<main.Genre>>;

export function GetTVRecommendations(arg1:number):Promise<main.TVSearchResult>;

export function GetTVSimilar(arg1:number):Promise<main.TVSearchResult>;

export function GetTVVideos(arg1:number):Promise<main.VideosResult>;

export function GetTrendingMovies(arg1:string,arg2:number):Promise<main.SearchResult>;

export function GetTrendingTV(arg1:string,arg2:number):Promise<main.TVSearchResult>;

export function SearchMovies(arg1:string,arg2:number):Promise<main.SearchResult>;

export function SearchTV(arg1:string,arg2:number):Promise<main.TVSearchResult>;

export function SetProxySettings(arg1:boolean,arg2:boolean):Promise<void>;

export function UpdateProxySettings(arg1:boolean,arg2:boolean):Promise<void>;
