// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnimationMovies(arg1) {
  return window['go']['main']['TMDB']['GetAnimationMovies'](arg1);
}

export function GetAnimationTV(arg1) {
  return window['go']['main']['TMDB']['GetAnimationTV'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['main']['TMDB']['GetCollection'](arg1);
}

export function GetGenres() {
  return window['go']['main']['TMDB']['GetGenres']();
}

export function GetImageURL(arg1, arg2) {
  return window['go']['main']['TMDB']['GetImageURL'](arg1, arg2);
}

export function GetMovieDetails(arg1) {
  return window['go']['main']['TMDB']['GetMovieDetails'](arg1);
}

export function GetMovieRecommendations(arg1) {
  return window['go']['main']['TMDB']['GetMovieRecommendations'](arg1);
}

export function GetMovieSimilar(arg1) {
  return window['go']['main']['TMDB']['GetMovieSimilar'](arg1);
}

export function GetMovieVideos(arg1) {
  return window['go']['main']['TMDB']['GetMovieVideos'](arg1);
}

export function GetPopularMovies(arg1) {
  return window['go']['main']['TMDB']['GetPopularMovies'](arg1);
}

export function GetPopularTV(arg1) {
  return window['go']['main']['TMDB']['GetPopularTV'](arg1);
}

export function GetSeasonDetails(arg1, arg2) {
  return window['go']['main']['TMDB']['GetSeasonDetails'](arg1, arg2);
}

export function GetTVDetails(arg1) {
  return window['go']['main']['TMDB']['GetTVDetails'](arg1);
}

export function GetTVGenres() {
  return window['go']['main']['TMDB']['GetTVGenres']();
}

export function GetTVRecommendations(arg1) {
  return window['go']['main']['TMDB']['GetTVRecommendations'](arg1);
}

export function GetTVSimilar(arg1) {
  return window['go']['main']['TMDB']['GetTVSimilar'](arg1);
}

export function GetTVVideos(arg1) {
  return window['go']['main']['TMDB']['GetTVVideos'](arg1);
}

export function GetTrendingMovies(arg1, arg2) {
  return window['go']['main']['TMDB']['GetTrendingMovies'](arg1, arg2);
}

export function GetTrendingTV(arg1, arg2) {
  return window['go']['main']['TMDB']['GetTrendingTV'](arg1, arg2);
}

export function SearchMovies(arg1, arg2) {
  return window['go']['main']['TMDB']['SearchMovies'](arg1, arg2);
}

export function SearchTV(arg1, arg2) {
  return window['go']['main']['TMDB']['SearchTV'](arg1, arg2);
}

export function SetProxySettings(arg1, arg2) {
  return window['go']['main']['TMDB']['SetProxySettings'](arg1, arg2);
}

export function UpdateProxySettings(arg1, arg2) {
  return window['go']['main']['TMDB']['UpdateProxySettings'](arg1, arg2);
}
