// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['TorrServer']['AddTorrent'](arg1, arg2, arg3, arg4);
}

export function AddTorrentFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['TorrServer']['AddTorrentFile'](arg1, arg2, arg3, arg4);
}

export function DropTorrent(arg1) {
  return window['go']['main']['TorrServer']['DropTorrent'](arg1);
}

export function Echo() {
  return window['go']['main']['TorrServer']['Echo']();
}

export function GetSettings() {
  return window['go']['main']['TorrServer']['GetSettings']();
}

export function GetStreamURL(arg1, arg2) {
  return window['go']['main']['TorrServer']['GetStreamURL'](arg1, arg2);
}

export function GetTorrent(arg1) {
  return window['go']['main']['TorrServer']['GetTorrent'](arg1);
}

export function GetTorrentStat(arg1) {
  return window['go']['main']['TorrServer']['GetTorrentStat'](arg1);
}

export function GetTorrents() {
  return window['go']['main']['TorrServer']['GetTorrents']();
}

export function PreloadTorrent(arg1, arg2) {
  return window['go']['main']['TorrServer']['PreloadTorrent'](arg1, arg2);
}

export function RemoveTorrent(arg1) {
  return window['go']['main']['TorrServer']['RemoveTorrent'](arg1);
}

export function SetBaseURL(arg1) {
  return window['go']['main']['TorrServer']['SetBaseURL'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['TorrServer']['SetSettings'](arg1);
}
