// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTorrent(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.Torrent>;

export function AddTorrentFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.Torrent>;

export function DropTorrent(arg1:string):Promise<void>;

export function Echo():Promise<boolean>;

export function GetSettings():Promise<Record<string, any>>;

export function GetStreamURL(arg1:string,arg2:number):Promise<string>;

export function GetTorrent(arg1:string):Promise<main.Torrent>;

export function GetTorrentStat(arg1:string):Promise<main.TorrentStat>;

export function GetTorrents():Promise<Array<main.Torrent>>;

export function PreloadTorrent(arg1:string,arg2:number):Promise<void>;

export function RemoveTorrent(arg1:string):Promise<void>;

export function SetBaseURL(arg1:string):Promise<void>;

export function SetSettings(arg1:Record<string, any>):Promise<void>;
